version: '3'
services:
  grpc-server:
    build: ./src/cmd/server
    ports:
      - "50051:50051"
  grpc-client:
    build: ./src/cmd/client
    depends_on:
      - grpc-server
    environment:
      - SERVER_ADDRESS=grpc-server:50051